name: cross-species-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bzip2=1.0.8=h2466b09_7
  - ca-certificates=2025.1.31=h56e8100_0
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.4.6=h537db12_1
  - liblzma=5.8.1=h2466b09_2
  - libsqlite=3.50.3=hf5d6505_1
  - libzlib=1.3.1=h2466b09_2
  - openssl=3.5.1=h725018a_0
  - pip=25.2=pyh8b19718_0
  - python=3.12.11=h3f84c4b_0_cpython
  - tk=8.6.13=h2c6b04d_2
  - ucrt=10.0.22621.0=h57928b3_1
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h818238b_31
  - vcomp14=14.44.35208=h818238b_31
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
    - asttokens==3.0.0
    - biopython==1.85
    - certifi==2025.7.14
    - charset-normalizer==3.4.2
    - colorama==0.4.6
    - decorator==5.2.1
    - docopt==0.6.2
    - et-xmlfile==2.0.0
    - executing==2.2.0
    - ftpretty==0.4.0
    - goatools==1.4.12
    - idna==3.10
    - ipython==9.4.0
    - ipython-pygments-lexers==1.1.1
    - jedi==0.19.2
    - jinja2==3.1.6
    - jsonpickle==4.1.1
    - markdown-it-py==3.0.0
    - markupsafe==3.0.2
    - matplotlib-inline==0.1.7
    - mdurl==0.1.2
    - networkx==3.5
    - numpy==2.3.2
    - openpyxl==3.1.5
    - packaging==25.0
    - pandas==2.3.1
    - parso==0.8.4
    - patsy==1.0.1
    - prompt-toolkit==3.0.51
    - pure-eval==0.2.3
    - pydot==4.0.1
    - pygments==2.19.2
    - pyparsing==3.2.3
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - pyvis==0.3.2
    - requests==2.32.4
    - rich==14.1.0
    - scipy==1.16.1
    - setuptools==80.0.0
    - six==1.17.0
    - stack-data==0.6.3
    - statsmodels==0.14.5
    - traitlets==5.14.3
    - tzdata==2025.2
    - urllib3==2.5.0
    - wcwidth==0.2.13
    - xlsxwriter==3.2.5